### ISSUE TITLE
Why delete=false in item.upload?

### ISSUE THREAD

**Issue by vxbinaca** [gdamdam/iagitup#6]
Wouldn't you want this to clean up after it's self if you were to say, script this like I want to?

**Comment by jjjake** [comment]
I talked with Gio, @vxbinaca -- yes, this makes sense (setting `delete=True` on upload, that is). Thanks for the suggestion!

**Comment by gdamdam** [comment]
yeah! thank you

**Comment by vxbinaca** [comment]
I was going to do a PR for this, but wanted to check the reasoning first 

thanks guys

Edit:

What does `headers={'x-archive-keep-old-version': '1'}` do?

**Comment by jjjake** [comment]
@vxbinaca When this header is set, old files will be moved to `/download/<id>/history/files/` when they are deleted rather than actually being deleted.

From https://archive.org/help/abouts3.txt:

> o Normally PUT and DELETE do not keep old versions of files around.
  To have the archive keep old versions of the object you can
  add the header:
  x-archive-keep-old-version:1
  Saved versions will be placed in history/files/$key.~N~
  (For multipart, the  x-archive-keep-old-version header must be
  specified at the time the multipart upload is completed)
